# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    #Encodeur : comment les mot de passes seront encodés
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        # ROLE_MODERATEUR : le modérateur peut gérer les salon de discussion
        ROLE_MODERATEUR: ROLE_USER
        # ROLE_ADMIN : l'admin est celui qui a créée un groupe, il en devient son admin et peut gérer celui-ci (ajout de membre, suppression de membre, etc.)
        ROLE_ADMIN: ROLE_USER
        # ROLE_SUPER_ADMIN : nous, les développeurs ayant accès à toutes les fonctionnalités complètes
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_MODERATEUR, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/ #platform/connexion|inscription
            anonymous: true
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:       logout
                target:     login
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
