<?php

namespace Amama\MelodyaBundle\Repository;

/**
 * GroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeRepository extends \Doctrine\ORM\EntityRepository {
    
    public function findMembresGroupes($idGroupe){
        
        $qb = $this->createQueryBuilder('g')->leftJoin('g.groupe_user', 'User')->addSelect('membres');

        return $qb->getQuery()->getResult();
    }
}
