<?php

namespace Amama\MelodyaBundle\Repository;

/**
 * InvitationsGroupeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitationsGroupeRepository extends \Doctrine\ORM\EntityRepository
{
}
